version: '3.8'

services:
  frontend:
    container_name: goup_front
    image: goup_front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
   


  backend:
    container_name: goup_admin
    image: goup_admin
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: goup_db
      DB_USERNAME: root
      DB_PASSWORD: RealNet1

  mysql:
    image: mysql:8.0
    container_name: goup-db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: RealNet1
      MYSQL_DATABASE: goup_db

volumes:
  mysql_data:
